### ISSUE TITLE
Question about Kafka statement

### ISSUE THREAD

**Issue by mensfeld** [KirollosSamy/InstaChat#1]
Hey, Karafka author here :) nice app you've built!

can you clarify for me this statement?

> One drawback of Kafka is handling retry mechanisms, thus a possibility here is to integrate both Kafka with Sidekiq to get the best of both worlds.

Karafka provides full end-to-end error and retry mechanisms + DLQ  setup out of the box:

https://karafka.io/docs/Error-handling-and-back-off-policy/
https://karafka.io/docs/Dead-Letter-Queue/

So I would love to know more about your use-case and why you think it does not match your use-case. Thanks!

**Comment by KirollosSamy** [comment]
Hi @mensfeld,

Thank you for reaching out. I sincerely appreciate the effort you’ve invested in developing Karafka, which I believe is valuable to the Ruby ecosystem.

To clarify, I was not referring to Karafka itself but rather aiming to highlight a general challenge developers may face when interfacing directly with Kafka, particularly, concerning error handling and retry mechanisms (to the best of my current understanding).

I’m thankful you highlighted Karafka’s features. As I’m still getting familiar with Karafka, I’m not fully aware of its capabilities. It’s reassuring to learn that Karafka addresses these challenges and handles them robustly.

While this project is focused more on learning purposes rather than production, I’ll definitely consider utilizing the features you’ve highlighted in future production scenarios.

Once again, thank you for your dedication and assistance!

**Comment by mensfeld** [comment]
Than you for your answer. If you would have any questions in the future please do not hesitate to reach out :)
